# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/COD/full_search_fast/full_search_fast.cache/wt [current_project]
set_property parent.project_path E:/COD/full_search_fast/full_search_fast.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths e:/COD/full_search_fast/ip_repo/full_search_1.0 [current_project]
set_property ip_output_repo e:/COD/full_search_fast/full_search_fast.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/hdl/full_search_wrapper.v
add_files E:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/full_search.bd
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_processing_system7_0_0/full_search_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_5/bd_052c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_11/bd_052c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_6/bd_052c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_7/bd_052c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_8/bd_052c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_9/bd_052c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_10/bd_052c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_1/bd_052c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/bd_0/ip/ip_1/bd_052c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_rst_ps7_0_100M_0/full_search_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_rst_ps7_0_100M_0/full_search_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_rst_ps7_0_100M_0/full_search_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/ip/full_search_auto_pc_0/full_search_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/full_search_ooc.xdc]
set_property is_locked true [get_files E:/COD/full_search_fast/full_search_fast.srcs/sources_1/bd/full_search/full_search.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top full_search_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef full_search_wrapper.dcp

catch { report_utilization -file full_search_wrapper_utilization_synth.rpt -pb full_search_wrapper_utilization_synth.pb }
