# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xci
# IP: The module: 'lab2_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xci
# IP: The module: 'lab2_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
