# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/full_search/full_search.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search || ORIG_REF_NAME==full_search}]

# IP: bd/full_search/ip/full_search_processing_system7_0_0/full_search_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_processing_system7_0_0 || ORIG_REF_NAME==full_search_processing_system7_0_0}]

# IP: bd/full_search/ip/full_search_full_search_0_0/full_search_full_search_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_full_search_0_0 || ORIG_REF_NAME==full_search_full_search_0_0}]

# IP: bd/full_search/ip/full_search_axi_smc_0/full_search_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_axi_smc_0 || ORIG_REF_NAME==full_search_axi_smc_0}]

# IP: bd/full_search/ip/full_search_rst_ps7_0_100M_0/full_search_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_rst_ps7_0_100M_0 || ORIG_REF_NAME==full_search_rst_ps7_0_100M_0}]

# IP: bd/full_search/ip/full_search_ps7_0_axi_periph_0/full_search_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_ps7_0_axi_periph_0 || ORIG_REF_NAME==full_search_ps7_0_axi_periph_0}]

# IP: bd/full_search/ip/full_search_auto_pc_0/full_search_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_search_auto_pc_0 || ORIG_REF_NAME==full_search_auto_pc_0}]

# XDC: bd/full_search/full_search_ooc.xdc
