# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab3/lab3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3 || ORIG_REF_NAME==lab3}]

# IP: bd/lab3/ip/lab3_processing_system7_0_0/lab3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_processing_system7_0_0 || ORIG_REF_NAME==lab3_processing_system7_0_0}]

# IP: bd/lab3/ip/lab3_match_0_0/lab3_match_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_match_0_0 || ORIG_REF_NAME==lab3_match_0_0}]

# IP: bd/lab3/ip/lab3_ps7_0_axi_periph_0/lab3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab3_ps7_0_axi_periph_0}]

# IP: bd/lab3/ip/lab3_rst_ps7_0_100M_0/lab3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab3_rst_ps7_0_100M_0}]

# IP: bd/lab3/ip/lab3_auto_pc_0/lab3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_auto_pc_0 || ORIG_REF_NAME==lab3_auto_pc_0}]

# XDC: bd/lab3/lab3_ooc.xdc
