# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/COD/lab3/lab3.cache/wt [current_project]
set_property parent.project_path E:/COD/lab3/lab3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths e:/COD/lab3/ip_repo/match_1.0 [current_project]
set_property ip_output_repo e:/COD/lab3/lab3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/COD/lab3/lab3.srcs/sources_1/bd/lab3/hdl/lab3_wrapper.v
add_files E:/COD/lab3/lab3.srcs/sources_1/bd/lab3/lab3.bd
set_property used_in_implementation false [get_files -all e:/COD/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_processing_system7_0_0/lab3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_rst_ps7_0_100M_0/lab3_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_rst_ps7_0_100M_0/lab3_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_rst_ps7_0_100M_0/lab3_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_auto_pc_0/lab3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/COD/lab3/lab3.srcs/sources_1/bd/lab3/lab3_ooc.xdc]
set_property is_locked true [get_files E:/COD/lab3/lab3.srcs/sources_1/bd/lab3/lab3.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab3_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef lab3_wrapper.dcp

catch { report_utilization -file lab3_wrapper_utilization_synth.rpt -pb lab3_wrapper_utilization_synth.pb }
