# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
# IP: The module: 'lab4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
# IP: The module: 'lab4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
