set_property SRC_FILE_INFO {cfile:E:/COD/lab4/lab4.srcs/constrs_1/new/lab4_wrapper.xdc rfile:../../lab4.srcs/constrs_1/new/lab4_wrapper.xdc id:1 rxprname:$PSRCDIR/constrs_1/new/lab4_wrapper.xdc} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[16]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[7]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[21]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[11]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[31]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[23]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[27]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[26]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[24]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[18]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[5]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[12]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[9]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[13]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[15]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[14]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[22]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[17]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[6]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[8]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[10]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[1]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[2]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[3]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[19]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[20]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[25]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[28]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[29]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {lab4_i/my_dma_0/inst/my_dma_v1_0_M00_AXI_inst/M_AXI_RDATA[30]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]

