# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab2/lab2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2 || ORIG_REF_NAME==lab2}]

# IP: bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_processing_system7_0_0 || ORIG_REF_NAME==lab2_processing_system7_0_0}]

# IP: bd/lab2/ip/lab2_compute_sad_0_0/lab2_compute_sad_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_compute_sad_0_0 || ORIG_REF_NAME==lab2_compute_sad_0_0}]

# IP: bd/lab2/ip/lab2_ps7_0_axi_periph_0/lab2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab2_ps7_0_axi_periph_0}]

# IP: bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab2_rst_ps7_0_100M_0}]

# IP: bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_auto_pc_0 || ORIG_REF_NAME==lab2_auto_pc_0}]

# XDC: bd/lab2/lab2_ooc.xdc
