# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/COD/lab2/lab2.cache/wt [current_project]
set_property parent.project_path E:/COD/lab2/lab2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths e:/COD/lab2/ip_repo/compute_sad_1.0 [current_project]
set_property ip_output_repo e:/COD/lab2/lab2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/COD/lab2/lab2.sdk/lab2_tb/Release/lab2_tb.elf
read_verilog -library xil_defaultlib E:/COD/lab2/lab2.srcs/sources_1/bd/lab2/hdl/lab2_wrapper.v
add_files E:/COD/lab2/lab2.srcs/sources_1/bd/lab2/lab2.bd
set_property used_in_implementation false [get_files -all e:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/COD/lab2/lab2.srcs/sources_1/bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/COD/lab2/lab2.srcs/sources_1/bd/lab2/lab2_ooc.xdc]
set_property is_locked true [get_files E:/COD/lab2/lab2.srcs/sources_1/bd/lab2/lab2.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab2_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef lab2_wrapper.dcp

catch { report_utilization -file lab2_wrapper_utilization_synth.rpt -pb lab2_wrapper_utilization_synth.pb }
