# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0.xci
# IP: The module: 'lab4_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0.xci
# IP: The module: 'lab4_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/COD/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
