# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab0_hw/lab0_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab0_hw || ORIG_REF_NAME==lab0_hw}]

# IP: bd/lab0_hw/ip/lab0_hw_processing_system7_0_0/lab0_hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab0_hw_processing_system7_0_0 || ORIG_REF_NAME==lab0_hw_processing_system7_0_0}]

# XDC: bd/lab0_hw/lab0_hw_ooc.xdc
